stages:
  - clean
  - test
  - deploy


format:
  stage: clean
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.9-slim
  before_script:
    - python -m pip install yapf toml
  script:
    - yapf -ri ./src ./tests


test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  script:
    - tox -e py38
  before_script:
    - pip install -r requirements_setup.txt
  artifacts:
    when: always
    reports:
      junit: dist/tests/report.xml
      coverage_report: 
        coverage_format: cobertura
        path: dist/tests/coverage.xml


pages:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.9-slim
  cache:
    key: tox-docs
    paths:
      - .tox
  before_script:
    - pip install -r requirements_setup.txt
  script:
    - tox -e docs
  after_script:
    - mv dist/docs/ public/
  artifacts:
    paths:
    - public
  only:
    - tags

build-package:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  script:
    - pip install twine build
    - python3 -m build --wheel
    - TWINE_PASSWORD=${TWINE_PASSWORD} TWINE_USERNAME=${TWINE_USERNAME} python3 -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags